export const ACTIONS = {
  ADD_CARD: "ADD_CARD",
  SHOW_ABOUT: "SHOW_ABOUT",
  SHOW_FILTERS: "SHOW_FILTERS",
  SORT_UPDATE_UP: "SORT_UPDATE_UP",
  SORT_UPDATE_DOWN: "ACTIONS.SORT_UPDATE_DOWN",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  SORT_LOW_TO_HIGHT: "SORT_LOW_TO_HIGHT",
  SORT_HIGHT_TO_LOW: "SORT_HIGHT_TO_LOW",
  ON_CLICK_SEARCH: "ON_CLICK_SEARCH",
  DELETE_CARD: "DELETE_CARD",
};
